codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "85...100"

  status:
    project:
      default:
        target: auto # will use the coverage from the base commit
        threshold: 2 # Allow to drop by 2%, and posting a success status.
    patch:
      default:
        target: 98 # Force 98% coverage with 2% threshold.
        threshold: 2 # Allow to drop by 2%, and posting a success status.
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, tree, files"
  behavior: default
  require_changes: no

ignore:
  - test/*
  - test/**/*

github_checks:
  annotations: true # Deprecated but very useful
