version: 2

sphinx:
  configuration: docs/userDocs/source/conf.py
  builder: html

build:
  image: latest
  apt_packages:
    - clang-10
    - cmake
    - libclang-10-dev
    - llvm-10-dev
    - llvm-10-tools
